// <auto-generated />
using System;
using CD.Web.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CD.Web.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CD.Web.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("NmCidade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NmCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            NmCidade = "Cidade1",
                            NmCliente = "Cli1"
                        },
                        new
                        {
                            IdCliente = 2,
                            NmCidade = "Cidade2",
                            NmCliente = "Cli2"
                        },
                        new
                        {
                            IdCliente = 3,
                            NmCidade = "Cidade3",
                            NmCliente = "Cli3"
                        },
                        new
                        {
                            IdCliente = 4,
                            NmCidade = "Cidade4",
                            NmCliente = "Cli4"
                        });
                });

            modelBuilder.Entity("CD.Web.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("DscProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("VlrUnitario")
                        .HasColumnType("real");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            IdProduto = 1,
                            DscProduto = "Produto 1",
                            VlrUnitario = 5f
                        },
                        new
                        {
                            IdProduto = 2,
                            DscProduto = "Produto 2",
                            VlrUnitario = 10f
                        },
                        new
                        {
                            IdProduto = 3,
                            DscProduto = "Produto 3",
                            VlrUnitario = 15f
                        },
                        new
                        {
                            IdProduto = 4,
                            DscProduto = "Produto 4",
                            VlrUnitario = 20f
                        });
                });

            modelBuilder.Entity("CD.Web.Models.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenda"));

                    b.Property<DateTime>("DthVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("QtdVenda")
                        .HasColumnType("int");

                    b.Property<float>("VlrUnitario")
                        .HasColumnType("real");

                    b.Property<float>("VlrUnitarioVenda")
                        .HasColumnType("real");

                    b.HasKey("IdVenda");

                    b.ToTable("Vendas");

                    b.HasData(
                        new
                        {
                            IdVenda = 1,
                            DthVenda = new DateTime(2023, 5, 19, 3, 34, 49, 293, DateTimeKind.Utc),
                            IdCliente = 1,
                            IdProduto = 1,
                            QtdVenda = 5,
                            VlrUnitario = 5f,
                            VlrUnitarioVenda = 5f
                        },
                        new
                        {
                            IdVenda = 2,
                            DthVenda = new DateTime(2023, 5, 19, 3, 34, 49, 293, DateTimeKind.Utc),
                            IdCliente = 1,
                            IdProduto = 2,
                            QtdVenda = 1,
                            VlrUnitario = 10f,
                            VlrUnitarioVenda = 10f
                        },
                        new
                        {
                            IdVenda = 3,
                            DthVenda = new DateTime(2023, 5, 19, 3, 34, 49, 293, DateTimeKind.Utc),
                            IdCliente = 1,
                            IdProduto = 3,
                            QtdVenda = 1,
                            VlrUnitario = 15f,
                            VlrUnitarioVenda = 15f
                        },
                        new
                        {
                            IdVenda = 4,
                            DthVenda = new DateTime(2023, 5, 19, 3, 34, 49, 293, DateTimeKind.Utc),
                            IdCliente = 2,
                            IdProduto = 1,
                            QtdVenda = 5,
                            VlrUnitario = 5f,
                            VlrUnitarioVenda = 5f
                        },
                        new
                        {
                            IdVenda = 5,
                            DthVenda = new DateTime(2023, 5, 19, 3, 34, 49, 293, DateTimeKind.Utc),
                            IdCliente = 2,
                            IdProduto = 2,
                            QtdVenda = 1,
                            VlrUnitario = 10f,
                            VlrUnitarioVenda = 10f
                        },
                        new
                        {
                            IdVenda = 6,
                            DthVenda = new DateTime(2023, 5, 19, 3, 34, 49, 293, DateTimeKind.Utc),
                            IdCliente = 3,
                            IdProduto = 1,
                            QtdVenda = 10,
                            VlrUnitario = 5f,
                            VlrUnitarioVenda = 6f
                        },
                        new
                        {
                            IdVenda = 7,
                            DthVenda = new DateTime(2023, 5, 19, 3, 34, 49, 293, DateTimeKind.Utc),
                            IdCliente = 3,
                            IdProduto = 3,
                            QtdVenda = 2,
                            VlrUnitario = 15f,
                            VlrUnitarioVenda = 15f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
